default: &default
  adapter: postgresql
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: rails_fileupload_development
  username: postgres
  password: 123

test:
  <<: *default
  database: rails_fileupload_test
  username: postgres
  password: 123
